import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Blog
        </h1>

        <p className={styles.description}>
          记录生活
        </p>

        <div className={styles.grid}>
          <a href='https://github.com/xuli-cooly' className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>全球最大的同性交友网站.</p>
          </a>

          <a href='https://www.wolai.com/fDq58x1Sy2gbweT6QNTYVf' className={styles.card}>
            <h2>学习篇 &rarr;</h2>
            <p>Learn More</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
